
# general configuration
image:
  registry: quay.io
  repository: openshift/origin-console
  image.tag: 4.14

ports:
  - name: http
    containerPort: 9000

serviceAccount:
  create: true

# Additonal configuration (serivce, ingress, stuff) can be found in the helmchart library "helmet"
# https://github.com/companyinfo/helm-charts/tree/main/charts/helmet#parameters

## @section RBAC parameters

## @param rbac.mode rbac mode choose between: view-cluster-wide (view all in the cluster, expected secrets) or admin-cluster-wide (edit all in the cluster)
rbac:
  mode: view-cluster-wide