apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ui-bridge
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]