# the "common.names.fullname" works but might be not sensed as beautiful 
# but i think its make no sense to add the kind in the resource name 
# (duplication in etcd)

# When the value is not "read-dashboard" the cluserrolebinding for 
# the read-cluster-wide is created
{{- if eq .Values.rbac.mode "view-cluster-wide" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-view-cluster-wide
  namespace: {{ include "common.names.namespace" . | quote }}
subjects:
- kind: ServiceAccount
  name: {{ include "helmet.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if eq .Values.rbac.mode "admin-cluster-wide" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-admin-cluster-wide
  namespace: {{ include "common.names.namespace" . | quote }}
subjects:
- kind: ServiceAccount
  name: {{ include "helmet.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}