apiVersion: v1
kind: Service
metadata:
  name: ui-bridge
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: ui-bridge
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9000
  selector:
    app: ui-bridge
  type: ClusterIP